bash

diff --git a/.azure/docker-build.yml b/.azure/docker-build.yml
--- a/.azure/docker-build.yml
+++ b/.azure/docker-build.yml
@@ -35,23 +35,22 @@ schedules:
       include: ["main"]
 
 jobs:
-  - job:
-    pool:
-      name: "lit-rtx-3090"
+  - job: testing
+    pool: "lit-rtx-3090"
     steps:
-  - bash: |
-      set -e
-      URL="https://download.agent.dev.azure.com/agent/4.252.0/vsts-agent-win-x64-4.252.0.zip"
-      STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --head --max-time 5 "$URL")
+      - bash: |
+          set -e
+          URL="https://download.agent.dev.azure.com/agent/4.252.0/vsts-agent-win-x64-4.252.0.zip"
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --head --max-time 5 "$URL")
 
-      if [ "$STATUS_CODE" -lt 400 ]; then
-        echo "Agent CDN is accessible. Status code: $STATUS_CODE"
-      else
-        echo "##vso[task.logissue type=warning]Can't access download.agent.dev.azure.com. Please make sure the access is not blocked by a firewall."
-        echo "Agent CDN is inaccessible. Please make sure the access is not blocked by a firewall"
-        exit 1
-      fi
-    displayName: "Test download.agent.dev.azure.com access"
+          if [ "$STATUS_CODE" -lt 400 ]; then
+            echo "Agent CDN is accessible. Status code: $STATUS_CODE"
+          else
+            echo "##vso[task.logissue type=warning]Can't access download.agent.dev.azure.com. Please make sure the access is not blocked by a firewall."
+            echo "Agent CDN is inaccessible. Please make sure the access is not blocked by a firewall"
+            exit 1
+          fi
+        displayName: "Test download.agent.dev.azure.com access"
 
   - job: build_push
     strategy:
